spring.application.name=portfolio-api
server.port=9999

#===========================================
#       DATABASE CONFIG
#===========================================
spring.datasource.url=jdbc:postgresql://localhost:5433/portfolio_db
spring.datasource.username=phaiecobyte
spring.datasource.password=phaiecobyte@123
spring.datasource.driver-class-name=org.postgresql.Driver

#hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update


#===========================================
# Telegram bot
#===========================================
telegram.bot.token=8269397469:AAGpecrkI-xmsvqzVfkR8NpyHqTmSn9XRdo
telegram.bot.chat-id=1120555808


#===========================================
#   Storage Config
#===========================================