spring.application.name=portfolio-api
server.port=9999

#Database Configuration for Development
spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio_db
spring.datasource.username=postgres
spring.datasource.password=phai
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#Database Configuration for production
#spring.datasource.url=jdbc:postgresql://dpg-d214pap5pdvs739n4dc0-a.singapore-postgres.render.com:5432/portfolio_db_l49j
#spring.datasource.username=phaiecobyte
#spring.datasource.password=Qyx0K6tVOZzIr8CFoeuSas7OKLlrBXdm
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update